apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-cluster-config
  namespace: development
data:
  valkey.conf: |
    cluster-enabled yes
    cluster-config-file /data/nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    protected-mode no
    bind 0.0.0.0
    port 6379
    cluster-announce-port 6379
    cluster-announce-bus-port 16379
