apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
  - configmap.yaml
  - service.yaml
  - statefulset.yaml
  - cluster-init-job.yaml
  - redisinsight.yaml
