apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: development
  labels:
    app: redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
        - name: redisinsight
          image: redis/redisinsight:latest
          ports:
            - containerPort: 5540
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redisinsight
  namespace: development
  labels:
    app: redisinsight
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5540
      targetPort: 5540
  selector:
    app: redisinsight
