apiVersion: v1
kind: Service
metadata:
  name: valkey-headless
  namespace: development
  labels:
    app: valkey-cluster
spec:
  clusterIP: None
  ports:
    - name: client
      port: 6379
      targetPort: 6379
    - name: gossip
      port: 16379
      targetPort: 16379
  selector:
    app: valkey-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: development
  labels:
    app: valkey-cluster
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 6379
      targetPort: 6379
  selector:
    app: valkey-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-lb
  namespace: development
  labels:
    app: valkey-cluster
spec:
  type: LoadBalancer
  ports:
    - name: client
      port: 6379
      targetPort: 6379
  selector:
    app: valkey-cluster
