apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
  namespace: development
  labels:
    app: valkey-cluster
spec:
  serviceName: valkey-headless
  replicas: 2
  selector:
    matchLabels:
      app: valkey-cluster
  template:
    metadata:
      labels:
        app: valkey-cluster
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:9.0.4-alpine
          command:
            - valkey-server
            - /etc/valkey/valkey.conf
          ports:
            - containerPort: 6379
              name: client
            - containerPort: 16379
              name: gossip
          volumeMounts:
            - name: config
              mountPath: /etc/valkey
            - name: data
              mountPath: /data
          readinessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: valkey-cluster-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
